/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.2.3.0 (NJsonSchema v9.13.35.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export class RegistrationCredentials implements IRegistrationCredentials {
    username!: string;
    email!: string;
    password!: string;

    constructor(data?: IRegistrationCredentials) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.username = data["username"];
            this.email = data["email"];
            this.password = data["password"];
        }
    }

    static fromJS(data: any): RegistrationCredentials {
        data = typeof data === 'object' ? data : {};
        let result = new RegistrationCredentials();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["username"] = this.username;
        data["email"] = this.email;
        data["password"] = this.password;
        return data; 
    }
}

export interface IRegistrationCredentials {
    username: string;
    email: string;
    password: string;
}

export class ResetPasswordWithTokenModel implements IResetPasswordWithTokenModel {
    userId?: string | undefined;
    token?: string | undefined;
    newPassword?: string | undefined;

    constructor(data?: IResetPasswordWithTokenModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.userId = data["userId"];
            this.token = data["token"];
            this.newPassword = data["newPassword"];
        }
    }

    static fromJS(data: any): ResetPasswordWithTokenModel {
        data = typeof data === 'object' ? data : {};
        let result = new ResetPasswordWithTokenModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["token"] = this.token;
        data["newPassword"] = this.newPassword;
        return data; 
    }
}

export interface IResetPasswordWithTokenModel {
    userId?: string | undefined;
    token?: string | undefined;
    newPassword?: string | undefined;
}

export class LoginCredentials implements ILoginCredentials {
    email!: string;
    password!: string;

    constructor(data?: ILoginCredentials) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.email = data["email"];
            this.password = data["password"];
        }
    }

    static fromJS(data: any): LoginCredentials {
        data = typeof data === 'object' ? data : {};
        let result = new LoginCredentials();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        data["password"] = this.password;
        return data; 
    }
}

export interface ILoginCredentials {
    email: string;
    password: string;
}

export class GuildMemberStats implements IGuildMemberStats {
    name?: string | undefined;
    realm?: string | undefined;
    level?: number | undefined;
    equippedIlvl?: number | undefined;
    class?: number | undefined;
    maximumIlvl?: number | undefined;
    achievementPoints?: number | undefined;
    mountCount?: number | undefined;
    petCount?: number | undefined;
    pvp2v2Rating?: number | undefined;
    pvp3v3Rating?: number | undefined;
    pvpRbgRating?: number | undefined;
    totalHonorableKills?: number | undefined;
    guildRank?: number | undefined;
    azeriteLevel?: number | undefined;
    raiderIoMplusScore?: number | undefined;

    constructor(data?: IGuildMemberStats) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.name = data["name"];
            this.realm = data["realm"];
            this.level = data["level"];
            this.equippedIlvl = data["equippedIlvl"];
            this.class = data["class"];
            this.maximumIlvl = data["maximumIlvl"];
            this.achievementPoints = data["achievementPoints"];
            this.mountCount = data["mountCount"];
            this.petCount = data["petCount"];
            this.pvp2v2Rating = data["pvp2v2Rating"];
            this.pvp3v3Rating = data["pvp3v3Rating"];
            this.pvpRbgRating = data["pvpRbgRating"];
            this.totalHonorableKills = data["totalHonorableKills"];
            this.guildRank = data["guildRank"];
            this.azeriteLevel = data["azeriteLevel"];
            this.raiderIoMplusScore = data["raiderIoMplusScore"];
        }
    }

    static fromJS(data: any): GuildMemberStats {
        data = typeof data === 'object' ? data : {};
        let result = new GuildMemberStats();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["realm"] = this.realm;
        data["level"] = this.level;
        data["equippedIlvl"] = this.equippedIlvl;
        data["class"] = this.class;
        data["maximumIlvl"] = this.maximumIlvl;
        data["achievementPoints"] = this.achievementPoints;
        data["mountCount"] = this.mountCount;
        data["petCount"] = this.petCount;
        data["pvp2v2Rating"] = this.pvp2v2Rating;
        data["pvp3v3Rating"] = this.pvp3v3Rating;
        data["pvpRbgRating"] = this.pvpRbgRating;
        data["totalHonorableKills"] = this.totalHonorableKills;
        data["guildRank"] = this.guildRank;
        data["azeriteLevel"] = this.azeriteLevel;
        data["raiderIoMplusScore"] = this.raiderIoMplusScore;
        return data; 
    }
}

export interface IGuildMemberStats {
    name?: string | undefined;
    realm?: string | undefined;
    level?: number | undefined;
    equippedIlvl?: number | undefined;
    class?: number | undefined;
    maximumIlvl?: number | undefined;
    achievementPoints?: number | undefined;
    mountCount?: number | undefined;
    petCount?: number | undefined;
    pvp2v2Rating?: number | undefined;
    pvp3v3Rating?: number | undefined;
    pvpRbgRating?: number | undefined;
    totalHonorableKills?: number | undefined;
    guildRank?: number | undefined;
    azeriteLevel?: number | undefined;
    raiderIoMplusScore?: number | undefined;
}

export class GuildFound implements IGuildFound {
    found?: boolean | undefined;
    realmName?: string | undefined;
    guildName?: string | undefined;

    constructor(data?: IGuildFound) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.found = data["found"];
            this.realmName = data["realmName"];
            this.guildName = data["guildName"];
        }
    }

    static fromJS(data: any): GuildFound {
        data = typeof data === 'object' ? data : {};
        let result = new GuildFound();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["found"] = this.found;
        data["realmName"] = this.realmName;
        data["guildName"] = this.guildName;
        return data; 
    }
}

export interface IGuildFound {
    found?: boolean | undefined;
    realmName?: string | undefined;
    guildName?: string | undefined;
}

export class AddMainToProfile implements IAddMainToProfile {
    playerName?: string | undefined;
    guildName?: string | undefined;
    playerRealmName?: string | undefined;
    guildRealmName?: string | undefined;
    profileId?: number | undefined;
    regionName?: string | undefined;

    constructor(data?: IAddMainToProfile) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.playerName = data["playerName"];
            this.guildName = data["guildName"];
            this.playerRealmName = data["playerRealmName"];
            this.guildRealmName = data["guildRealmName"];
            this.profileId = data["profileId"];
            this.regionName = data["regionName"];
        }
    }

    static fromJS(data: any): AddMainToProfile {
        data = typeof data === 'object' ? data : {};
        let result = new AddMainToProfile();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["playerName"] = this.playerName;
        data["guildName"] = this.guildName;
        data["playerRealmName"] = this.playerRealmName;
        data["guildRealmName"] = this.guildRealmName;
        data["profileId"] = this.profileId;
        data["regionName"] = this.regionName;
        return data; 
    }
}

export interface IAddMainToProfile {
    playerName?: string | undefined;
    guildName?: string | undefined;
    playerRealmName?: string | undefined;
    guildRealmName?: string | undefined;
    profileId?: number | undefined;
    regionName?: string | undefined;
}

export class PlayerMain implements IPlayerMain {
    id?: number | undefined;
    name?: string | undefined;
    notes?: string | undefined;
    officerNotes?: string | undefined;
    alts?: PlayerAlt[] | undefined;

    constructor(data?: IPlayerMain) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.name = data["name"];
            this.notes = data["notes"];
            this.officerNotes = data["officerNotes"];
            if (data["alts"] && data["alts"].constructor === Array) {
                this.alts = [] as any;
                for (let item of data["alts"])
                    this.alts!.push(PlayerAlt.fromJS(item));
            }
        }
    }

    static fromJS(data: any): PlayerMain {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerMain();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["notes"] = this.notes;
        data["officerNotes"] = this.officerNotes;
        if (this.alts && this.alts.constructor === Array) {
            data["alts"] = [];
            for (let item of this.alts)
                data["alts"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IPlayerMain {
    id?: number | undefined;
    name?: string | undefined;
    notes?: string | undefined;
    officerNotes?: string | undefined;
    alts?: PlayerAlt[] | undefined;
}

export class PlayerAlt implements IPlayerAlt {
    id?: number | undefined;
    name?: string | undefined;

    constructor(data?: IPlayerAlt) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.name = data["name"];
        }
    }

    static fromJS(data: any): PlayerAlt {
        data = typeof data === 'object' ? data : {};
        let result = new PlayerAlt();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        return data; 
    }
}

export interface IPlayerAlt {
    id?: number | undefined;
    name?: string | undefined;
}

export class GuildProfile implements IGuildProfile {
    id?: number | undefined;
    creator?: CreatorStub | undefined;
    profileName?: string | undefined;
    guildName?: string | undefined;
    realm?: string | undefined;
    region?: string | undefined;

    constructor(data?: IGuildProfile) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.creator = data["creator"] ? CreatorStub.fromJS(data["creator"]) : <any>undefined;
            this.profileName = data["profileName"];
            this.guildName = data["guildName"];
            this.realm = data["realm"];
            this.region = data["region"];
        }
    }

    static fromJS(data: any): GuildProfile {
        data = typeof data === 'object' ? data : {};
        let result = new GuildProfile();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["creator"] = this.creator ? this.creator.toJSON() : <any>undefined;
        data["profileName"] = this.profileName;
        data["guildName"] = this.guildName;
        data["realm"] = this.realm;
        data["region"] = this.region;
        return data; 
    }
}

export interface IGuildProfile {
    id?: number | undefined;
    creator?: CreatorStub | undefined;
    profileName?: string | undefined;
    guildName?: string | undefined;
    realm?: string | undefined;
    region?: string | undefined;
}

export class CreatorStub implements ICreatorStub {
    id?: string | undefined;
    email?: string | undefined;
    username?: string | undefined;

    constructor(data?: ICreatorStub) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.email = data["email"];
            this.username = data["username"];
        }
    }

    static fromJS(data: any): CreatorStub {
        data = typeof data === 'object' ? data : {};
        let result = new CreatorStub();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["email"] = this.email;
        data["username"] = this.username;
        return data; 
    }
}

export interface ICreatorStub {
    id?: string | undefined;
    email?: string | undefined;
    username?: string | undefined;
}

export class FullGuildProfile implements IFullGuildProfile {
    id?: number | undefined;
    creator?: CreatorStub | undefined;
    profileName?: string | undefined;
    guildName?: string | undefined;
    realm?: StoredRealm | undefined;
    region?: string | undefined;
    players?: BlizzardPlayer[] | undefined;
    mains?: PlayerMain[] | undefined;

    constructor(data?: IFullGuildProfile) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.creator = data["creator"] ? CreatorStub.fromJS(data["creator"]) : <any>undefined;
            this.profileName = data["profileName"];
            this.guildName = data["guildName"];
            this.realm = data["realm"] ? StoredRealm.fromJS(data["realm"]) : <any>undefined;
            this.region = data["region"];
            if (data["players"] && data["players"].constructor === Array) {
                this.players = [] as any;
                for (let item of data["players"])
                    this.players!.push(BlizzardPlayer.fromJS(item));
            }
            if (data["mains"] && data["mains"].constructor === Array) {
                this.mains = [] as any;
                for (let item of data["mains"])
                    this.mains!.push(PlayerMain.fromJS(item));
            }
        }
    }

    static fromJS(data: any): FullGuildProfile {
        data = typeof data === 'object' ? data : {};
        let result = new FullGuildProfile();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["creator"] = this.creator ? this.creator.toJSON() : <any>undefined;
        data["profileName"] = this.profileName;
        data["guildName"] = this.guildName;
        data["realm"] = this.realm ? this.realm.toJSON() : <any>undefined;
        data["region"] = this.region;
        if (this.players && this.players.constructor === Array) {
            data["players"] = [];
            for (let item of this.players)
                data["players"].push(item.toJSON());
        }
        if (this.mains && this.mains.constructor === Array) {
            data["mains"] = [];
            for (let item of this.mains)
                data["mains"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IFullGuildProfile {
    id?: number | undefined;
    creator?: CreatorStub | undefined;
    profileName?: string | undefined;
    guildName?: string | undefined;
    realm?: StoredRealm | undefined;
    region?: string | undefined;
    players?: BlizzardPlayer[] | undefined;
    mains?: PlayerMain[] | undefined;
}

export class StoredRealm implements IStoredRealm {
    id?: number | undefined;
    name?: string | undefined;
    regionId?: number | undefined;

    constructor(data?: IStoredRealm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["id"];
            this.name = data["name"];
            this.regionId = data["regionId"];
        }
    }

    static fromJS(data: any): StoredRealm {
        data = typeof data === 'object' ? data : {};
        let result = new StoredRealm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["regionId"] = this.regionId;
        return data; 
    }
}

export interface IStoredRealm {
    id?: number | undefined;
    name?: string | undefined;
    regionId?: number | undefined;
}

export class BlizzardPlayer implements IBlizzardPlayer {
    guildName?: string | undefined;
    playerName?: string | undefined;
    realmName?: string | undefined;
    class?: number | undefined;
    level?: number | undefined;

    constructor(data?: IBlizzardPlayer) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.guildName = data["guildName"];
            this.playerName = data["playerName"];
            this.realmName = data["realmName"];
            this.class = data["class"];
            this.level = data["level"];
        }
    }

    static fromJS(data: any): BlizzardPlayer {
        data = typeof data === 'object' ? data : {};
        let result = new BlizzardPlayer();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["guildName"] = this.guildName;
        data["playerName"] = this.playerName;
        data["realmName"] = this.realmName;
        data["class"] = this.class;
        data["level"] = this.level;
        return data; 
    }
}

export interface IBlizzardPlayer {
    guildName?: string | undefined;
    playerName?: string | undefined;
    realmName?: string | undefined;
    class?: number | undefined;
    level?: number | undefined;
}

export class Realm implements IRealm {
    name?: string | undefined;
    id?: number | undefined;
    slug?: string | undefined;

    constructor(data?: IRealm) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.name = data["name"];
            this.id = data["id"];
            this.slug = data["slug"];
        }
    }

    static fromJS(data: any): Realm {
        data = typeof data === 'object' ? data : {};
        let result = new Realm();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["id"] = this.id;
        data["slug"] = this.slug;
        return data; 
    }
}

export interface IRealm {
    name?: string | undefined;
    id?: number | undefined;
    slug?: string | undefined;
}